### ISSUE TITLE
QAT Paper checklist

### ISSUE THREAD

**Issue by DeepCowProductions** [fhswf/eki-transformer-dev#39]
Open TODOs:
- [ ] https://github.com/fhswf/eki-transformer-dev/issues/32

Possible Results:
- [ ] https://github.com/fhswf/eki-transformer-dev/issues/37 
- [ ] https://github.com/fhswf/eki-transformer-dev/issues/38
